import Head from 'next/head';

import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { useEffect } from 'react';
import Kommunalka from '@/ApiConnecor/Auth';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { Typography, Layout, Menu, theme, Row, Col, Space, Card, Steps, Divider, Grid } from 'antd';

import Image from 'next/image';
import HeaderBanner from '../components/HeaderBanner';
import profilePic from '../images/express.png';
import profilePic2 from '../images/mongo.png';
import profilePi3 from '../images/nodejs.png';
import profilePi4 from '../images/next-js.svg';
import { LoadingOutlined, SmileOutlined, SolutionOutlined, UserOutlined } from '@ant-design/icons';
const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const { Content } = Layout;
  const { Title, Text } = Typography;
  const { useBreakpoint } = Grid;
  const screens = useBreakpoint();
  console.log(screens);

  return (
    <>
      <Head>
        <title>Kommunalka - инструмент для записи показаний</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Content
          style={{
            backgroundColor: '#fff',
            // height: ` ${typeof window === 'object' && window.innerHeight / 2}px` || '600',
            width: '100%',
          }}>
          <Row>
            <Col span={(screens.md && 12) || 24}>
              <Title style={{ margin: '30px' }}>Инструмент для записи показаний</Title>
              <Title style={{ margin: '30px' }} level={3}>
                Записывайте показания ваших счетчиков ,указывайте коэффиценты - получайте результат
              </Title>
            </Col>
            <Col span={(screens.md && 12) || 24}>
              <HeaderBanner />
            </Col>
          </Row>
        </Content>
        <Content
          style={{
            backgroundColor: '#fff',

            width: '100%',
            display: 'flex',

            alignItems: 'center',
            justifyContent: 'center',
          }}>
          <Title level={2}>Легко в использовании</Title>
        </Content>
        <Content
          style={{
            backgroundColor: '#f0f6fa',
            height: ` ${(typeof window === 'object' && window.innerHeight / 2 - 64) || 400}px`,
            width: '100%',
            display: 'flex',

            alignItems: 'center',
            justifyContent: 'center',
            padding: 30,
          }}>
          <Steps
            direction={(screens?.xl && 'horizontal') || 'vertical'}
            items={[
              {
                title: 'Регистрация',
                status: 'finish',
                icon: <UserOutlined />,
              },
              {
                title: 'Указание показателей',
                status: 'finish',
                icon: <SolutionOutlined />,
              },
              {
                title: 'Ежемесяное внесение данных',
                status: 'finish',
                icon: <SolutionOutlined />,
              },
              {
                title: 'Подсчет суммы к оплате',
                status: 'finish',
                icon: <SmileOutlined />,
              },
            ]}
          />
        </Content>

        <Content
          style={{
            width: '100%',
            display: 'flex',
            backgroundColor: '#f0f6fa',
            alignItems: 'center',
            justifyContent: 'center',
          }}>
          <Title level={2}>Реализовано с помощью </Title>
        </Content>
        <Content
          style={{
            width: '100%',
            height: ` ${(typeof window === 'object' && window.innerHeight / 2 - 64) || 400}px`,
          }}>
          <Row
            style={{ width: '100%', height: 'inherit', marginTop: 10 }}
            align="middle"
            justify="center"
            gutter={[16, 16]}>
            <Col span={(screens.md && 6) || 24}>
              <Card bodyStyle={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
                <Image src={profilePic2} height="100" alt="Picture of the author" />

                <Text>Mongo DB - NoSQL база данных</Text>
              </Card>
            </Col>
            <Col span={(screens.md && 6) || 24}>
              <Card bodyStyle={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
                <Image src={profilePic} height="100" alt="Picture of the author" />
                <Text>Express JS - фреймворк бекэнд</Text>
              </Card>
            </Col>
            <Col span={(screens.md && 6) || 24}>
              <Card bodyStyle={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
                <Image src={profilePi4} height="100" alt="Picture of the author" />

                <Text>Next JS - фреймворк фронтэнда</Text>
              </Card>
            </Col>
            <Col span={(screens.md && 6) || 24}>
              <Card bodyStyle={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
                <Image src={profilePi3} height="100" alt="Picture of the author" />

                <Text>Node JS - программная платформа</Text>
              </Card>
            </Col>
          </Row>
        </Content>
      </main>
    </>
  );
}
